# Generated by Django 4.0.4 on 2022-05-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='cumpleaños',
            new_name='fecha_nacimiento',
        ),
    ]
